name: .NET CI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet Packages
      run: nuget restore CarRentalSystem.csproj

    - name: Build Project
      run: msbuild CarRentalSystem.csproj /p:Configuration=Release
