name: .NET CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Create and Build Fresh Project
      run: |
        # سنقوم بإنشاء مشروع جديد كلياً داخل السيرفر ليتجاهل ملفات المستودع المعطوبة
        dotnet new console -n SuccessTest
        cd SuccessTest
        dotnet build
